module.exports={
    mode:"production",
    entry:{
        index:"./src/index.js",//數組會合並為一個bundle
        other:"./src/mutiply.js"
    },
    output:{
        filename:"[name].js"
    },
    //devtool:"source-map"
    optimization:{
        runtimeChunk:"single",
        splitChunks:{
            cacheGroups:{
                commons:{
                    chunks:"initial",
                    minChunks:2,
                    minSize:0
                },
                vendor:{
                    test:/node_modules/,
                    chunks:"initial",
                    name:"vendor",
                    enforce:true
                }
            }
        }
    }
}
//runtime chunk 引入 
//